--------------------------------------------------------
-- Archivo creado  - martes-octubre-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALQUILER
--------------------------------------------------------

  CREATE TABLE "ALQUILER"."ALQUILER" 
   (	"VEHICULO" VARCHAR2(50 BYTE), 
	"CLIENTE" VARCHAR2(50 BYTE), 
	"HORAS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CIUDAD
--------------------------------------------------------

  CREATE TABLE "ALQUILER"."CIUDAD" 
   (	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "ALQUILER"."CLIENTE" 
   (	"IDENTIFICACION" VARCHAR2(50 BYTE), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(50 BYTE), 
	"CIUDAD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LINEA
--------------------------------------------------------

  CREATE TABLE "ALQUILER"."LINEA" 
   (	"NOMBRE_LINEA" VARCHAR2(20 BYTE), 
	"NOMBRE_MARCA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MARCA
--------------------------------------------------------

  CREATE TABLE "ALQUILER"."MARCA" 
   (	"NOMBRE_MARCA" VARCHAR2(20 BYTE), 
	"PAIS_ORIGEN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIENDA
--------------------------------------------------------

  CREATE TABLE "ALQUILER"."TIENDA" 
   (	"NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VEHICULO
--------------------------------------------------------

  CREATE TABLE "ALQUILER"."VEHICULO" 
   (	"PLACA" VARCHAR2(50 BYTE), 
	"COSTO" NUMBER(20,2), 
	"IMAGEN" VARCHAR2(50 BYTE), 
	"LINEA" VARCHAR2(20 BYTE), 
	"MARCA" VARCHAR2(20 BYTE), 
	"MODELO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ALQUILER.ALQUILER
SET DEFINE OFF;
REM INSERTING into ALQUILER.CIUDAD
SET DEFINE OFF;
REM INSERTING into ALQUILER.CLIENTE
SET DEFINE OFF;
REM INSERTING into ALQUILER.LINEA
SET DEFINE OFF;
Insert into ALQUILER.LINEA (NOMBRE_LINEA,NOMBRE_MARCA) values ('prueba10','Ford');
Insert into ALQUILER.LINEA (NOMBRE_LINEA,NOMBRE_MARCA) values ('323','Mazda');
REM INSERTING into ALQUILER.MARCA
SET DEFINE OFF;
Insert into ALQUILER.MARCA (NOMBRE_MARCA,PAIS_ORIGEN) values ('Mazda','Japon');
Insert into ALQUILER.MARCA (NOMBRE_MARCA,PAIS_ORIGEN) values ('Renault','Francia');
Insert into ALQUILER.MARCA (NOMBRE_MARCA,PAIS_ORIGEN) values ('Ford','Estados Unidos');
REM INSERTING into ALQUILER.TIENDA
SET DEFINE OFF;
REM INSERTING into ALQUILER.VEHICULO
SET DEFINE OFF;
Insert into ALQUILER.VEHICULO (PLACA,COSTO,IMAGEN,LINEA,MARCA,MODELO) values ('ILV40D2','4000','null','323','Mazda','2013');
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALQUILER"."CLIENTE_PK" ON "ALQUILER"."CLIENTE" ("IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CIUDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALQUILER"."CIUDAD_PK" ON "ALQUILER"."CIUDAD" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VEHICULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALQUILER"."VEHICULO_PK" ON "ALQUILER"."VEHICULO" ("PLACA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIENDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALQUILER"."TIENDA_PK" ON "ALQUILER"."TIENDA" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MARCA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALQUILER"."MARCA_PK" ON "ALQUILER"."MARCA" ("NOMBRE_MARCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LINEA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALQUILER"."LINEA_PK" ON "ALQUILER"."LINEA" ("NOMBRE_LINEA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ALQUILER"."CLIENTE" MODIFY ("CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."CLIENTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."CLIENTE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."CLIENTE" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."CLIENTE" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."CLIENTE" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINEA
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."LINEA" ADD CONSTRAINT "LINEA_PK" PRIMARY KEY ("NOMBRE_LINEA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ALQUILER"."LINEA" MODIFY ("NOMBRE_MARCA" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."LINEA" MODIFY ("NOMBRE_LINEA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULO
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."VEHICULO" ADD CONSTRAINT "VEHICULO_PK" PRIMARY KEY ("PLACA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ALQUILER"."VEHICULO" MODIFY ("MODELO" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."VEHICULO" MODIFY ("MARCA" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."VEHICULO" MODIFY ("LINEA" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."VEHICULO" MODIFY ("COSTO" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."VEHICULO" MODIFY ("PLACA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MARCA
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."MARCA" ADD CONSTRAINT "MARCA_PK" PRIMARY KEY ("NOMBRE_MARCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ALQUILER"."MARCA" MODIFY ("PAIS_ORIGEN" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."MARCA" MODIFY ("NOMBRE_MARCA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIENDA
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."TIENDA" ADD CONSTRAINT "TIENDA_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ALQUILER"."TIENDA" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CIUDAD
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."CIUDAD" ADD CONSTRAINT "CIUDAD_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ALQUILER"."CIUDAD" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALQUILER
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."ALQUILER" MODIFY ("HORAS" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."ALQUILER" MODIFY ("CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ALQUILER"."ALQUILER" MODIFY ("VEHICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALQUILER
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."ALQUILER" ADD CONSTRAINT "ALQUILER_CLIENTE_FK1" FOREIGN KEY ("CLIENTE")
	  REFERENCES "ALQUILER"."CLIENTE" ("IDENTIFICACION") ENABLE;
  ALTER TABLE "ALQUILER"."ALQUILER" ADD CONSTRAINT "ALQUILER_VEHICULO_FK1" FOREIGN KEY ("VEHICULO")
	  REFERENCES "ALQUILER"."VEHICULO" ("PLACA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."CLIENTE" ADD CONSTRAINT "CLIENTE_CIUDAD_FK1" FOREIGN KEY ("CIUDAD")
	  REFERENCES "ALQUILER"."CIUDAD" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LINEA
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."LINEA" ADD CONSTRAINT "LINEA_MARCA_FK1" FOREIGN KEY ("NOMBRE_MARCA")
	  REFERENCES "ALQUILER"."MARCA" ("NOMBRE_MARCA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULO
--------------------------------------------------------

  ALTER TABLE "ALQUILER"."VEHICULO" ADD CONSTRAINT "VEHICULO_LINEA_FK1" FOREIGN KEY ("LINEA")
	  REFERENCES "ALQUILER"."LINEA" ("NOMBRE_LINEA") ENABLE;
  ALTER TABLE "ALQUILER"."VEHICULO" ADD CONSTRAINT "VEHICULO_MARCA_FK1" FOREIGN KEY ("MARCA")
	  REFERENCES "ALQUILER"."MARCA" ("NOMBRE_MARCA") ENABLE;
--------------------------------------------------------
--  DDL for Package PKG_LINEA
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "ALQUILER"."PKG_LINEA" AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

END PKG_LINEA;

/
--------------------------------------------------------
--  DDL for Package PKG_MARCA
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "ALQUILER"."PKG_MARCA" AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

END PKG_MARCA;

/
--------------------------------------------------------
--  DDL for Package PKG_VEHICULO
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "ALQUILER"."PKG_VEHICULO" AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

END PKG_VEHICULO;

/
